# Generated by Django 2.2.13 on 2020-06-25 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDepartamento', models.CharField(max_length=50)),
                ('codigoISO', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreZona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=50)),
                ('idDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='idZona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Zona'),
        ),
    ]
