# Generated by Django 2.2.13 on 2020-06-25 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dui', models.CharField(max_length=9)),
                ('idDepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Departamento')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.Municipio')),
            ],
        ),
    ]
